config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :users
  devise_scope :user do
    get '/users/new/:token', controller: 'users', action: 'new',
    as: 'invited_new_user'

    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :invitations, only: [:new, :create]

  get '/home', to: 'home#show'

  root 'home#show'
end

app/models/user.rb
class User < ApplicationRecord
  include Roles

  has_one :invitation, foreign_key: :email, primary_key: :email

  define_roles :developer, :owner, :admin

  # WARNING: Enabling registerable will allow users to sign up for the
  # application on their own.  This raises security requirements for the app.
  # We prefer to use a invitation sign up model where administrators invite
  # all new users to the application (This is enabled by the default app). 
  #
  # HERE BE DRAGONS.

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
         :validatable
  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ResourcesController
  resource_model User

  before_action :authenticate_user!, except: [:create]

  def new
    sign_out
    @user = User.new
    @user.email = invitation.email unless invitation.blank?
    authorize @user
    @token = params[:token]
  end

  def create
    @user = User.new(permitted_attributes(User))
    @user.invitation&.assign_attributes token: params[:token]
    authorize @user

    respond_to do |format|
      if @user.save
        @user.invitation.accept
        # dont require sign in if user created from token
        bypass_sign_in @user if current_user.blank?
        format.html { redirect_to root_path, notice: "Account successfully created."}
      else
        format.html {render action: 'new'}
      end
    end
  end

  def update
    @user.assign_attributes(permitted_attributes(@user))
    authorize @user

    respond_to do |format|
      if @user.save
        # if the password is present (we're updating it) and current_user is
        # the user being updated, we need to sign back in for ourselves
        bypass_sign_in @user if updating_self? && updating_password?
        format.html { redirect_to @user, notice: "User updated."}
      else
        format.html { render action: 'edit'}
      end
    end
  end

  private

  def invitation
    @invitation ||= InvitationsQuery.first_with_token params[:token]
  end

  def authenticate_user!
    super unless invitation.present? && invitation.accepted_at.nil?
  end

  def updating_self?
    current_user.id == @user.id
  end

  def updating_password?
    params[:user][:password].present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user, html: {class: 'stacked-form'}) do |f| %>
  <%= hidden_field_tag :token, token %>

  <section>
    <div class="stacked-form-field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, placeholder: "Enter First Name", class: "full-width" %>
    </div>
    <div class="stacked-form-field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, placeholder: "Enter Last Name", class: "full-width" %>
    </div>
    <div class="stacked-form-field">
      <%= f.label :email %>
      <%= f.email_field :email,  placeholder: "Enter Email", class: "full-width" %>
    </div>
  </section>
  <section>
    <div class="stacked-form-field">
      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "Enter Password", class: "full-width" %>
    </div>
    <div class="stacked-form-field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "full-width" %>
    </div>
  </section>

  <% if user.errors.any? %>
    <div class="margin-top-normal">
      <ul class="no-list-style anim-slide-fade-up">
        <% user.errors.full_messages.each do |message| %>
          <li class="font-small text-error"><%= fa_icon('exclamation-circle', text: message) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-right margin-top-medium">
    <%= link_to "Back to users", users_path %>
    <%= f.button "Save", class: "btn-primary margin-left-normal" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="page-container-single-form">
  <h2> <%= @user.name %> </h2>
  <%= render 'form', user: @user, token: nil %>
</div>

app/views/users/index.html.erb
<div class="page-container">
  <header class="flex-baseline">
    <h2>Users</h2>
    <div class="flex-right">
      <%= link_to fa_icon('user-plus', text: 'Invite a User'), new_invitation_path, class: "btn-secondary" if current_user.admin? %>
    </div>
  </header>

  <div class="margin-top-medium">
    <table class="index-table">
      <thead>
        <tr>
          <%= sortable_column_header :name, sort_by: :first_name %>
          <%= sortable_column_header :email %>
        </tr>
      </thead>

      <tbody class="basic-card-no-padding">
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.name, user %></td>
            <td><%= user.email %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @users, inner_window: 1, outer_window: 0,
        previous_label: fa_icon('angle-left'), next_label: fa_icon('angle-right') %>
  </div>
</div>

app/views/users/new.html.erb
<div class="page-container-single-form">
  <h2 class="center">Welcome!</h2>
  
  <%= render 'form', user: @user, token: @token %>
</div>

app/views/users/show.html.erb
<div class="page-container-single-form">
  <h2> <%= @user.name %> </h2>
  <%= render 'form', user: @user, token: nil %>
</div>